# Generated by Django 3.2.4 on 2021-07-21 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_no', models.IntegerField(default=0, unique=True)),
                ('cell_pollution', models.DecimalField(decimal_places=8, max_digits=10)),
                ('cell_width', models.DecimalField(decimal_places=8, max_digits=10)),
                ('cell_thickness', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField(default=0, unique=True)),
                ('unit_condition', models.CharField(max_length=100)),
                ('unit_strength', models.DecimalField(decimal_places=9, max_digits=10)),
                ('unit_purity', models.DecimalField(decimal_places=8, max_digits=10)),
                ('unit_precision', models.DecimalField(decimal_places=8, max_digits=10)),
                ('unit_cell_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='api_server.cellmodel', to_field='cell_no')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('user_password', models.CharField(max_length=256, unique=True)),
                ('user_fullname', models.CharField(max_length=16)),
                ('user_phone', models.CharField(max_length=16)),
                ('user_email', models.CharField(max_length=128)),
                ('user_role', models.CharField(max_length=8)),
                ('user_comments', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer_lot', models.IntegerField()),
                ('wafer_wafer', models.IntegerField()),
                ('wafer_group', models.IntegerField()),
                ('wafer_punchSeq', models.IntegerField()),
                ('wafer_week', models.IntegerField()),
                ('wafer_day', models.CharField(max_length=100)),
                ('wafer_shift', models.CharField(max_length=100)),
                ('wafer_worker', models.IntegerField()),
                ('wafer_stepper', models.IntegerField()),
                ('wafer_conductivity', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_strength', models.DecimalField(decimal_places=9, max_digits=10)),
                ('wafer_purity', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_precision', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_temperature', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_humidity', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_pollution', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_width', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_thickness', models.DecimalField(decimal_places=9, max_digits=10)),
                ('wafer_noise', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_mq', models.DecimalField(decimal_places=9, max_digits=10)),
                ('wafer_mac', models.DecimalField(decimal_places=9, max_digits=10)),
                ('wafer_logic', models.DecimalField(decimal_places=8, max_digits=10)),
                ('wafer_signal_A', models.DecimalField(decimal_places=6, max_digits=10)),
                ('wafer_signal_B', models.DecimalField(decimal_places=6, max_digits=10)),
                ('wafer_date', models.CharField(max_length=100)),
                ('wafer_die_x', models.IntegerField()),
                ('wafer_die_y', models.IntegerField()),
                ('wafer_unit_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='api_server.unitmodel', to_field='unit_no')),
            ],
        ),
    ]
